host: https://uat-www.cf.nzpost.co.nz

api:
  host: https://api.uat.nzpost.co.nz/digital
  locations-url: /postshop-locations/v1/locations
  suggestions-url: /postshop-locations/v1/suggestions
  locations-url-v2: /postshop-locations/v2/locations
  suggestions-url-v2: /postshop-locations/v2/suggestions
  parcelAddress-url: /parcel-service/v1/parceladdress
